### ISSUE TITLE
Consider using the BioAssay Ontology for general assay terms?

### ISSUE THREAD

**Issue by egonw** [sobolevnrm/npo#1]
I noticed that there are many assay related terms, like cytotoxicity and end points like IC50. One option is to import the CC-BY BioAssay Ontology for this...

**Comment by vedina** [comment]
from my experience  NPO has a better coverage for modern assays compared to BioAssay  (although it will be good to consolidate these across Bioportal)

**Comment by egonw** [comment]
Make sure to test it against BAO 2.0 [0] and we can contribute things to BAO anyway, like I am doing for Open PHACTS too.

0.http://www.bioassayontology.org/index.php?option=com_content&view=article&id=96&Itemid=137

**Comment by egonw** [comment]
@linikujp you may be interested in this BAO issue in the NPO too...

**Comment by linikujp** [comment]
@egonw Thanks for letting me know.  I will look into NPO, and see how can we align these two. Please let me know if you have some suggestions.
