### ISSUE TITLE
Is this in the identifiers.org registry?

### ISSUE THREAD

**Issue by ariutta** [sobolevnrm/npo#4]
Hello,

I am trying to use this resource in conjunction with the identifiers.org registry. It doesn't appear to be included there yet, so it would be great to file a ticket to create a new collection to represent it. Here is where you can file the ticket:
http://sourceforge.net/p/identifiers-org/new-collection/new/

I would file it myself, but I want to be sure the collection is described correctly, so it would be more appropriate for someone from the project to file the ticket.

Thanks!

**Comment by egonw** [comment]
Hi Anders,

ontologies not commonly get registered in identifiers.org, only databases... then again, I guess ChEBI is registered, but that is a clear outlier ontology, which has a huge number of instances... now, NPO seems to have this too, with a number of specific nanomaterials, but these are still really classes...

I will email Nick Juty...

Egon

**Comment by ariutta** [comment]
Sounds reasonable. Thanks!

**Comment by cmungall** [comment]
As you seem to be compatible with OBO ontologies, reusing these as appropriate, consider registering on obofoundry.org via https://github.com/OBOFoundry/OBOFoundry.github.io/issues/new

**Comment by egonw** [comment]
> consider registering on obofoundry.org

@cmungall, I cannot register it, because the "new ontology" template puts restrictions on the license, and expects things that do not exist yet. The license not being CC0/CC-BY may be a blocker.

**Comment by egonw** [comment]
I will close this issue, because the original thing will likely not happen, ontology improvement is to be picked up (OBO registration we will try later), and bioregistry.io has it.
