### ISSUE TITLE
backport nanomaterials from the eNanoMapper ontology

### ISSUE THREAD

**Issue by egonw** [sobolevnrm/npo#7]
See https://github.com/enanomapper/ontologies/blob/master/internal/npo-ext.owl

**Comment by egonw** [comment]
cc @laurent2207

**Comment by lwinckers** [comment]
What is exact action for this issue?

**Comment by egonw** [comment]
Backporting is the term for taking changes (patches) from a downstream project to the upstream project. So, the extensions made in ENM for NPO should be applied here.
